INSERT IGNORE INTO team (ID, NAME)
VALUES (1, 'Uruguay'),
       (2, 'Portugal'),
       (3, 'France'),
       (4, 'Argentina'),
       (5, 'Brazil'),
       (6, 'Mexico'),
       (7, 'Belgium'),
       (8, 'Japan'),
       (9, 'Spain'),
       (10, 'Russia'),
       (11, 'Croatia'),
       (12, 'Denmark'),
       (13, 'Sweden'),
       (14, 'Switzerland'),
       (15, 'Colombia'),
       (16, 'England');